steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build container image"
    env:
      - "DOCKER_BUILDKIT=1"
    args:
      [
        "build",
        ".",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-molecules/train:latest",
        "-f",
        "dockerfiles/train.dockerfile",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: "Push container image"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-molecules/train:latest",
      ]
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-molecules/train:latest"
options:
  logging: CLOUD_LOGGING_ONLY
